// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'}
  ],
  
  // Manual sidebar entries can be added here
  // These will supplement the auto-generated sidebar
};

module.exports = sidebars;
