const fs = require('fs');
const path = require('path');

// Paths (relative to the function's execution context)
const projectRoot = path.join(__dirname, '..', '..', '..');
const navbarPath = path.join(projectRoot, 'data/navbar.json');
const collectionsConfig = {
  docs: {
    path: path.join(projectRoot, 'docs'),
    indexTemplate: (label) => `---
title: ${label}
sidebar_label: ${label}
sidebar_position: 1
---

# ${label}

Welcome to the ${label} section. This page was automatically created.
`,
    categoryTemplate: (label, docId) => ({
      label,
      position: 1,
      link: {
        type: 'doc',
        id: docId
      }
    })
  },
  blog: {
    path: path.join(projectRoot, 'blog'),
    indexTemplate: (label) => `---
title: ${label}
authors: []
tags: []
---

# ${label}

Welcome to the ${label} blog section.
`
  },
  custom: {
    path: projectRoot,
    indexTemplate: (label) => `---
title: ${label}
---

# ${label}

This is a custom section.
`
  }
};

// Read current navbar data
function getNavbarData() {
  try {
    const data = fs.readFileSync(navbarPath, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    console.error('Error reading navbar.json:', error);
    return { items: [] };
  }
}

// Create folder structure for navbar item
function createNavbarFolder(item) {
  if (!item.to || !item.label) return null;

  // Extract path components (e.g., "/docs/tutorial-basics" -> ["docs", "tutorial-basics"])
  const pathComponents = item.to.replace(/^\/+/, '').split('/');
  
  if (pathComponents.length < 1) return null;

  const firstFolder = pathComponents[0];
  const folderPath = path.join(projectRoot, firstFolder);
  
  // Check if first-level folder already exists
  if (!fs.existsSync(folderPath)) {
    // Create the first-level folder (e.g., "docs", "blog", "my-new-section")
    fs.mkdirSync(folderPath, { recursive: true });
    console.log(`Created first-level folder: ${firstFolder}`);
    
    // Create _category_.json for Docusaurus sidebar
    const categoryPath = path.join(folderPath, '_category_.json');
    const categoryData = {
      label: item.label,
      position: 1,
      link: {
        type: 'doc',
        id: `${firstFolder}/index`
      }
    };
    fs.writeFileSync(categoryPath, JSON.stringify(categoryData, null, 2));
    console.log(`Created _category_.json for: ${firstFolder}`);
  }

  // Create subfolders if they exist (e.g., "tutorial-basics" in "docs")
  if (pathComponents.length > 1) {
    let currentPath = folderPath;
    
    for (let i = 1; i < pathComponents.length; i++) {
      const subFolderName = pathComponents[i];
      currentPath = path.join(currentPath, subFolderName);
      
      if (!fs.existsSync(currentPath)) {
        fs.mkdirSync(currentPath, { recursive: true });
        console.log(`Created subfolder: ${subFolderName}`);
        
        // Create _category_.json for subfolders
        if (i === pathComponents.length - 1) {
          const categoryPath = path.join(currentPath, '_category_.json');
          const categoryData = {
            label: item.label,
            position: 1,
            link: {
              type: 'doc',
              id: `${pathComponents.slice(0, i + 1).join('/')}/index`
            }
          };
          fs.writeFileSync(categoryPath, JSON.stringify(categoryData, null, 2));
          console.log(`Created _category_.json for: ${subFolderName}`);
        }
      }
    }
  }

  // Create index.md in the final folder
  const finalFolderPath = path.join(projectRoot, ...pathComponents);
  const indexPath = path.join(finalFolderPath, 'index.md');
  const frontmatter = `---
title: ${item.label}
sidebar_label: ${item.label}
sidebar_position: 1
---

# ${item.label}

Welcome to the ${item.label} section. This page was automatically created when you added the "${item.label}" navbar item.

You can now create additional markdown files in this folder to build out your documentation.
`;

  fs.writeFileSync(indexPath, frontmatter);
  console.log(`Created index.md in: ${pathComponents.join('/')}`);
  
  return pathComponents.join('/');
}

// Update sidebars.js to include new folder
function updateSidebars(newFolderPath) {
  try {
    const sidebarsContent = fs.readFileSync(sidebarsPath, 'utf8');
    
    // Extract the folder name from the path (e.g., "docs/tutorial-basics" -> "tutorial-basics")
    const folderName = newFolderPath.split('/').pop();
    
    // Check if the folder is already in the sidebar
    if (sidebarsContent.includes(folderName)) {
      console.log(`Folder ${folderName} already in sidebar`);
      return;
    }

    // Check if we need to replace the autogenerated sidebar
    if (sidebarsContent.includes("tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]")) {
      // Replace with manual sidebar including new category
      const updatedContent = sidebarsContent.replace(
        /tutorialSidebar: \[\{type: 'autogenerated', dirName: '\.'\}\]/,
        `tutorialSidebar: [
  {type: 'autogenerated', dirName: '.'},
  {
    type: 'category',
    label: '${folderName}',
    items: [${folderName}],
  },
]`
      );
      fs.writeFileSync(sidebarsPath, updatedContent);
      console.log(`Updated sidebars.js with new folder: ${folderName}`);
    } else {
      // Add to existing manual sidebar
      const categoryInsert = `  {
    type: 'category',
    label: '${folderName}',
    items: [${folderName}],
  },`;
      
      // Insert before the closing bracket
      const updatedContent = sidebarsContent.replace(
        /(\s*\}\s*;?\s*export default sidebars;)/,
        `${categoryInsert}\n$1`
      );
      fs.writeFileSync(sidebarsPath, updatedContent);
      console.log(`Updated sidebars.js with new folder: ${folderName}`);
    }
  } catch (error) {
    console.error('Error updating sidebars.js:', error);
  }
}

// Main function to process navbar changes
function processNavbarChanges() {
  const currentData = getNavbarData();
  const existingFolders = new Set();
  
  // Get existing folders from docs directory
  if (fs.existsSync(docsPath)) {
    const folders = fs.readdirSync(docsPath, { withFileTypes: true })
      .filter(dirent => dirent.isDirectory())
      .map(dirent => dirent.name);
    folders.forEach(folder => existingFolders.add(folder));
  }

  let createdFolders = [];
  
  // Process each navbar item
  currentData.items.forEach(item => {
    if (item.to && item.label) {
      const folderPath = item.to.replace(/^\/+/, '');
      if (folderPath && !existingFolders.has(folderPath)) {
        const createdFolder = createNavbarFolder(item);
        if (createdFolder) {
          updateSidebars(createdFolder);
          existingFolders.add(createdFolder);
          createdFolders.push(createdFolder);
        }
      }
    }
  });

  return createdFolders;
}

// Netlify function handler
exports.handler = async (event, context) => {
  try {
    if (event.httpMethod === 'GET') {
      // For GET requests, just process existing navbar changes
      console.log('Processing navbar changes...');
      const createdFolders = processNavbarChanges();
      return {
        statusCode: 200,
        body: JSON.stringify({
          message: 'Navbar processing completed',
          createdFolders: createdFolders
        })
      };
    } else if (event.httpMethod === 'POST') {
      // For POST requests, handle creating new folders
      const { navbarData, action } = JSON.parse(event.body);
      
      if (!navbarData || !navbarData.collectionType || !navbarData.label) {
        return {
          statusCode: 400,
          body: JSON.stringify({ 
            success: false, 
            error: 'Missing required fields' 
          })
        };
      }

      const collectionConfig = collectionsConfig[navbarData.collectionType];
      if (!collectionConfig) {
        return {
          statusCode: 400,
          body: JSON.stringify({ 
            success: false, 
            error: 'Invalid collection type' 
          })
        };
      }

      // Create the folder structure
      const pathComponents = navbarData.to.replace(/^\/+/, '').split('/');
      let currentPath = collectionConfig.path;
      
      // Create each level of the folder structure
      for (const component of pathComponents.slice(1)) {
        currentPath = path.join(currentPath, component);
        if (!fs.existsSync(currentPath)) {
          fs.mkdirSync(currentPath, { recursive: true });
        }
      }

      // Create index file
      const indexPath = path.join(currentPath, 'index.md');
      if (!fs.existsSync(indexPath)) {
        fs.writeFileSync(
          indexPath,
          collectionConfig.indexTemplate(navbarData.label)
        );
      }

      // Create _category_.json if it's a docs collection
      if (navbarData.collectionType === 'docs') {
        const categoryPath = path.join(currentPath, '_category_.json');
        const docId = pathComponents.slice(1).join('/') + '/index';
        
        if (!fs.existsSync(categoryPath)) {
          fs.writeFileSync(
            categoryPath,
            JSON.stringify(
              collectionConfig.categoryTemplate(navbarData.label, docId),
              null,
              2
            )
          );
        }
      }

      // Update sidebars if it's a docs collection
      if (navbarData.collectionType === 'docs') {
        updateSidebars(pathComponents.join('/'));
      }

      return {
        statusCode: 200,
        body: JSON.stringify({
          success: true,
          path: currentPath.replace(projectRoot, '')
        })
      };
    }

    return {
      statusCode: 405,
      body: JSON.stringify({
        success: false,
        error: 'Method not allowed'
      })
    };
  } catch (error) {
    console.error('Error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ 
        success: false, 
        error: 'Internal server error',
        message: error.message
      })
    };
  }
};